#!/bin/bash
set -x
cd $OPENSHIFT_DATA_DIR

if [ -d $OPENSHIFT_DATA_DIR/tomcat8 ]
then
    # Java 1.8 set env
    export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_72/bin:$PATH
    export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_72/

    # Ant 1.9 set env
    ANT_HOME=$OPENSHIFT_DATA_DIR/apache-ant-1.9.6
    ANT_OPTS="-Xms256M -Xmx512M"
    PATH=$PATH:$HOME/bin:$ANT_HOME/bin
    export ANT_HOME ANT_OPTS PATH

	cd tomcat8/bin
	./startup.sh
    exit 0
else
    # Java 1.8 Installation and Configuration
    cd $OPENSHIFT_DATA_DIR

    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u72-b15/jdk-8u72-linux-x64.tar.gz
    tar -zxf jdk-8u72-linux-x64.tar.gz
    export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_72/bin:$PATH
    export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_72/

    # Apache Ant Installation and Configuration
    cd $OPENSHIFT_DATA_DIR
    wget https://www.apache.org/dist/ant/binaries/apache-ant-1.9.7-bin.zip
    unzip apache-ant-1.9.7-bin.zip
    ANT_HOME=$OPENSHIFT_DATA_DIR/apache-ant-1.9.7
    ANT_OPTS="-Xms256M -Xmx512M"
    PATH=$PATH:$HOME/bin:$ANT_HOME/bin
    export ANT_HOME ANT_OPTS PATH

    cd $OPENSHIFT_DATA_DIR
	mkdir -p source dependencies
	cd source/
	git clone https://github.com/apache/tomcat80.git
	cd tomcat80/
	mv build.properties.default build.properties
  OLD_PATH={user.home}/tomcat-build-libs
	NEW_PATH={user.home}/app-root/data/dependencies
	sed -i "s|$OLD_PATH|$NEW_PATH|g" build.properties
	sed -i "s#depends=\"package,build-docs,build-tomcat-jdbc\"#depends=\"package,build-tomcat-jdbc\"#g" build.xml
	ant clean
	ant
	cd $OPENSHIFT_DATA_DIR
	mkdir tomcat8
	cd tomcat8
	cp -r ../source/tomcat80/output/build/* .
	cd conf/
	ip=$OPENSHIFT_DIY_IP
	sed -i "s#<Server\s*port=\(\"8005\"\)\(.*\)#<Server address=\"$ip\" port=\"18005\" \2#g" server.xml
	sed -i "s#<Connector\s*port=\(\"8080\"\)\(.*\)#<Connector address=\"$ip\" port=\"8080\" \2#g;" server.xml
	sed -i "s#<Connector\s*port=\(\"8009\"\)\(.*\)#<Connector address=\"$ip\" port=\"18009\" \2#g" server.xml
	sed -i "s#redirectPort=\"8443\"#redirectPort=\"18443\"#g" server.xml
	cd ../bin
	./startup.sh
fi
